quote:flip`time`sym`bid`ask`bsize`asize`mode`ex!"tsffjjcc":\()
trade:flip`time`sym`price`size`stop`cond`ex!"tsfjbcc":\()
fill:flip`date`sym`time`price`size`stop`cond`ex!"dstfjbcc":\()
mtm:flip`time`date`sym`close!"ndsf":\()
signal:flip`sym`date`signal`time!"sdin":\()