quote:flip`time`sym`bid`ask`bsize`asize`mode`ex!"tsffjjcc"$\:()
trade:flip`time`sym`price`size`stop`cond`ex!"tsfjbcc"$\:()
mtm:flip`time`date`sym`close!"ndsf"$\:()
signal:flip`sym`date`signal`time!"sdin"$\:()
order:flip`sym`date`signal`time!"sdin"$\:()
fill:flip`date`sym`time`price`size!"dsnfj"$\:() / flip`date`sym`time`price`size`stop`cond`ex!"dstfjbcc"$:\()
