.servers.startup[]
hbtt: .servers.gethandlebytype[`bttickerplant;`any]
hswitch: .servers.gethandlebytype[`btswitch;`any]
btt: .sub.getsubscriptionhandles[`bttickerplant;();()!()]
subinfo:.sub.subscribe[`order;`;1b;0b;first btt]